* MacOS Closest thing to EXWM
So [[https://github.com/ch11ng/exwm][EXWM]] is great, but it only works for linux and I can't use it in my
MacOS builds. This is because MacOS is not open with its window
manager and native apps aren't actually written in X anyway I guess.

My Mac usage is probably not going anywhere -- hardware-wise, I'm not sure there's a competitor for
laptops. So, I thought I would take some notes on how I might get an EXWM-like experience with MacOs software.

- Tiling window manager
- Modal key bindings
- Ivy-like searching for mah stuff


I think this can be accomplished by using a few tools:
** Yabai Window Manager
https://github.com/koekeishiya/yabai
Tiling window manager that provides split/focus/float capabilities
** SKHD Hotkeys, Karabiner-Elements
https://github.com/koekeishiya/skhd
https://karabiner-elements.pqrs.org/ Importantly, skhd allows for
modal hotkeys. This will allow me to create a command map behind an
escape-hatch key (likely hyper) The escape-hatch key should probably
be capslock for my workflow, so I need a piece of software that will
remap capslock to some modifier key (again, my assumption is hyper)

** Rough Potential Layout:
- Most of the time I am in SKHD "normal" mode, meaning all keys except capslock go to the application
- When I press capslock (hyper), am taken to SKHD "command" mode.
- Commands then map to purpose, occasionally going to another submap:
  - For instance, "w" goes to window maps
- Some basic behavior:
  - CAPS-w-j: go to the window down
  - CAPS-w-k: go to the window up
  - CAPS-w-h: go to the window left
  - CAPS-w-l: go to the window right

Then there are "selector" commands, which should bring up a searchable
map. The plan is to use emacs + ivy as the backend here. For instance:

CAPS-w-w: select window

This should:
- Invoke Yabai to open a floating window
- Open an emacsclient in this window
- Full-screen an ivy-select for:
  - All windows open in yabai
  - All windows open in emacs
- Based on the selection, an ivy-function should feed back into yabai to select the window


THIS. COULD. WORK

One kinda benefit: this could end my need for ivy-pos-frame: I could
hook directly into yabai with a floating frame and not worry about
being "in-frame" at all!

*** Steps (probably not ordered right)
**** TODO Get Emacs client/daemon running on mac to your liking
**** TODO Build an ivy function that invokes an external program
Possibly just firefox to keep it simple. The point is to learn how to
do the ivy backend.
**** TODO Figure out how to make ivy-select buffer the whole screen
**** TODO Figure out how to get ivy to kill its frame on the way out
**** TODO Figure out how to invoke emacsclient with the command to get you right to that ivy buffer
#ivyclient baby
**** TODO Get CAPSLOCK escaped
**** TODO Get SKHD working and invoking ivy-client
**** TODO Cut over to Yabai (maybe try it out on AWS first)
BE SURE TO BACK UP BEFORE DOING THIS

